### ISSUE TITLE
How to build to jar?

### ISSUE THREAD

**Issue by NikeboyHU** [cFerg/MineJava#4]
pom.xml is not update/uploaded, so... couldn't create jar file, or... Any tips for me?

**Comment by cFerg** [comment]
Jar can't be properly created yet, because it still lacks some files in the dependencies.

I still have (roughly) 30~ more classes to add in the dependencies

Some days, like the weekend, I did a lot.

Throughout the week, I'm at work, so only can do a few each day.

I'll make a status section later - Then I can post when it should be done

**Comment by NikeboyHU** [comment]
Okey, thank you.
